### ISSUE TITLE
URL's with # 

### ISSUE THREAD

**Issue by GeorgeWarren3C** [guilryder/chrome-extensions#10]
I have URL in the format https://servername.domain.local/Word/Word/Word/#/Word/Word

In the options I have the following setup:
{title} - {protocol}://{hostname}{port}/{path}{args}

However I am only able to see the below in the tab
https://servername.domain.local/Word/Word/Word/ 

The part with the # and stuff after is key so really need this to be visible in tab

I did have a look through the support and reviews on the google store etc and there was a mention of this issue on Apr 4, 2015 but you responded to say you had tested and couldn't replicate. 

Am I missing something in the config, or is it not possible to show the # and bits after?

Thanks 

George

**Comment by guilryder** [comment]
Your configuration lacks `{hash}`. That's why the extension doesn't include the fragment in titles.
