### ISSUE TITLE
Manifest v3, xframe_ignore

### ISSUE THREAD

**Issue by filipot** [guilryder/chrome-extensions#11]
Hi, do you know if it is possible to make something simular with manifest v3, or would v3 kill the needed functionality?

**Comment by guilryder** [comment]
Yes, xframe_ignore is actually simpler with Manifest V3 (no Javascript needed): https://github.com/guilryder/chrome-extensions/tree/xframe_ignore_MV3

Migrating urlintitle is more involved and riskier: https://github.com/guilryder/chrome-extensions/tree/urlintitle_MV3

Disclaimer: I drafted the changes last year when Manifest v3 was still undergoing changes. It's possible they don't work any more. I didn't publish the update to avoid risking to break existing users. Publishing changes to the Chrome store is always a gamble.

**Comment by filipot** [comment]
@guilryder Ah thats cool! Thanks!
