### ISSUE TITLE
Support Firefox.

### ISSUE THREAD

**Issue by BEEDELLROKEJULIANLOCKHART** [guilryder/chrome-extensions#12]
My rationale is available at "https://github.com/ThomazPom/Moz-Ext-Ignore-X-Frame-Options/issues/20#issue-1291535056".

**Comment by guilryder** [comment]
This repository is for Chrome/Chromium/Edge extensions only. I don't use Firefox and don't have the time or motivation to go through https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Build_a_cross_browser_extension: another extension store approval process, another round of testing. **Please feel free to do it yourself**, the license is very permissive and you have my permission :)

When Chrome forces the migration to Manifest v3, this extension will have no Javascript at all: just a manifest and a trivial static rules file (see the `xframe_ignore_MV3` branch). I don't know what "supporting Firefox" would mean at that point: no code to share. If Firefox is Manifest v3-compatible, then the extension can be published as-is; if not, there is nothing of value to reuse.
