### ISSUE TITLE
Microsoft Edge chromium Support 

### ISSUE THREAD

**Issue by F3000** [guilryder/chrome-extensions#2]
Is it possible that you can upload your plugin into the Microsoft App Store ?

**Comment by guilryder** [comment]
Good idea! I uploaded the extension to the Microsoft Edge store, the extension is in review.

**Comment by guilryder** [comment]
Microsoft Edge extension published: https://microsoftedge.microsoft.com/addons/detail/ofmgkjflhpkiobhgebefnjncenhjciad
