### ISSUE TITLE
Url in Title stops updating the title of pages that delete <title> under <head>

### ISSUE THREAD

**Issue by Yozer** [guilryder/chrome-extensions#5]
Hi!
First of all, thanks for the Url in Title extension. It's very useful when used together with KeePass.
Recently I noticed that it stopped working for some websites in Edge. Would it be possible to fix the issue?
For example etoro.com
It works correctly in Chrome.

Edge 90.0.818.8 Beta

**Comment by guilryder** [comment]
More details needed to reproduce & fix the issue: detailed instructions, symptoms, etc. The extension handles https://www.etoro.com/ fine on my machine with Edge version 89.0.774.57 (Official build) (64-bit). I didn't try other URLs or websites.

**Comment by Yozer** [comment]
Interesting. It might be related to my beta version of Edge? Do you have an option to check that?
It was working without any issues for a long time so maybe version 90 broke something.

**Comment by guilryder** [comment]
Perhaps, we have no way to tell for sure at this stage. I don't understand what you mean by "Do you have an option to check that?"

To diagnose I need reproducible instructions: the exact steps you take to see the issue. See [this article](https://www.chiark.greenend.org.uk/~sgtatham/bugs.html) to get the idea.

**Comment by Yozer** [comment]
I was just thinking that you might have an Edge 90 Beta to confirm that this is the reason for this bug.
Here are the detailed steps to reproduce this issue:

1. Install a recent version of Edge/Chrome/Edge Beta. I successfully reproduced it on ```Edge 90.0.818.8 Beta``` and ```Chrome  89.0.4389.90```
2. Install "Url in title" 3.0.1
3. Configure it to show: ```TEST {hostname}{port}```
4. Go to [https://www.etoro.com/login](https://www.etoro.com/login)

Expected result. Window name should be equal to ```TEST www.etoro.com```
Actual result: Window name is equal to ```eToro```

**Comment by guilryder** [comment]
Fixed in Url in title version 3.0.2.
